# Generated by Django 3.1.7 on 2021-03-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_game_last_move"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="owner_score",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="visitor_score",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="game",
            name="_moves",
            field=models.TextField(default="[]"),
        ),
    ]
